run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    #- depguard
    #- dogsled
    #- dupl
    - errcheck
    #- exhaustive
    #- funlen
    - gas
    #- gochecknoinits
    - goconst
    - gocritic
    #- gocyclo
    #- gofmt
    - goimports
    - golint
    #- gomnd
    #- goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    #- lll
    - maligned
    - megacheck
    #- misspell
    #- nakedret
    - noctx
    #- nolintlint
    #- rowserrcheck
    #- scopelint
    #- staticcheck
    - structcheck
    #- stylecheck
    #- typecheck
    - unconvert
    - unparam
    #- unused
    - varcheck
    #- whitespace
    - errorlint
    - makezero
    - nestif
    - prealloc
    - nilerr
  fast: false

issues:
  exclude:
    - "composite literal uses unkeyed fields"
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - unparam
        - bodyclose
    - path: fixtures.go
      linters:
        - gosec
