// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package ports

// User model.
type User struct {
	Email  string   `json:"email"`
	Groups []string `json:"groups"`
	Login  string   `json:"login"`

	// Unique name for the given user.
	Name string `json:"name"`
}

// User model.
type GetUserResponse = User

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	Users []User `json:"users"`
}

// SearchUsersResponse defines model for SearchUsersResponse.
type SearchUsersResponse = []string

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Group *ListUsersParamsGroup `form:"group,omitempty" json:"group,omitempty"`
}

// ListUsersParamsGroup defines parameters for ListUsers.
type ListUsersParamsGroup string
